version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kurobe-postgres
    environment:
      POSTGRES_USER: kurobe
      POSTGRES_PASSWORD: kurobe
      POSTGRES_DB: kurobe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/postgres/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kurobe"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kurobe-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (uncomment when using Docker for development)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: kurobe-backend
  #   environment:
  #     - DATABASE_URL=postgresql://kurobe:kurobe@postgres:5432/kurobe
  #     - REDIS_URL=redis://redis:6379/0
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #     - ./config:/app/config

  # Frontend (uncomment when using Docker for development)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: kurobe-frontend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default:
    name: kurobe-network
